---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: /:title ## disables post output
timezone: Asia/Jakarta
lsi: false
markdown: kramdown


### content configuration ###
title:       "1S3M4U Blog"
keywords:    "Belajar Linux | Kali Linux | Ubuntu | Debian | Mikrotik | Hacking | Exploit"
description: "Web Page 1S3M4U Repository on github | Tempat belajar dan mengajar"
source_link: "https://1s3m4u.github.io"
favicon:     "img/favicon.ico"
touch_icon:  "img/apple-touch-icon.png"
google_analytics_key: UA- ## put YOUR key here to enable tracking! (blank to disable)


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  blue:      '#49a7e9'
  green:     '#9bcf2f'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#0fbfcf'

kramdown:
  auto_ids:  false
